#!/bin/sh

# verify — Verify Confidence

# Confidence (https://github.com/melusina-org/cl-confidence)
# This file is part of Confidence.
#
# Copyright © 2019–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${subrdir:=${TOPLEVELDIR}/subr}

. "${subrdir}/stdlib.sh"


verify_main()
{
    : 'Do nothing.'
}

verify_main "$@"

# End of file `verify'
