name: 'Run testsuite on MacOS BigSur'
on:
  - workflow_dispatch
  - push
jobs:
  run-testsuite:
    runs-on: 'macos-11'
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Install MacPorts'
        id: 'macports'
        uses: melusina-org/gha-install-macports@v1
      - name: 'Install Quicklisp in CI environment'
        run: >-
          sbcl
          --load '${{ steps.macports.outputs.prefix }}/share/cl-quicklisp/quicklisp.lisp'
          --eval '(quicklisp-quickstart:install)'
          --eval '(ql-util:without-prompting (ql:add-to-init-file))'
          --quit
      - name: 'Add Workspace to Quicklisp local project directories'
        run: >-
          printf '\n(pushnew \043p\"%s\" ql:*local-project-directories*)\n' "${GITHUB_WORKSPACE}" >> ~/.sbclrc
      - name: 'Run the testsuite'
        run: 'development/testsuite'
