name: 'Run testsuite on BigSur'
on:
  - workflow_dispatch
  - push
jobs:
  run-testsuite:
    runs-on: 'macos-11'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: 'Install MacPorts'
        uses: melusina-org/gha-install-macports@v1
        with:
          ports: >-
            sbcl +fancy
            cl-quicklisp
      - name: 'Install Quicklisp in CI environment'
        run: >-
          sbcl
          --load '/opt/local/share/cl-quicklisp/quicklisp.lisp'
          --eval '(quicklisp-quickstart:install)'
          --eval '(ql-util:without-prompting (ql:add-to-init-file))'
          --quit
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Run the testsuite'
        run: 'development/testsuite'
